version: "3"

networks:
    monitor-net:
        driver: bridge

services:

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        container_name: grafana
        networks:
            - monitor-net

    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins
        volumes:
            - ../../monitoring/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
        networks:
            - monitor-net

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        expose:
            - 9090
        container_name: prometheus
        volumes:
            - ../../monitoring/prometheus:/etc/prometheus
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        networks:
            - monitor-net
